[tool.poetry]
name = "FastApi-RESTful"
version = "0.3.0"
description = "Quicker FastApi developing tools"
license = "MIT"
authors = ["Yuval Levi"]
readme = "README.md"
homepage = "https://fastapi-restful.netlify.app"
repository = "https://github.com/yuval9313/fastapi-utils"
documentation = "https://fastapi-restful.netlify.app"
keywords = ["fastapi", "OOP", "RESTful"]
classifiers = [
    "Intended Audience :: Information Technology",
    "Intended Audience :: System Administrators",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python",
    "Topic :: Internet",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development",
    "Typing :: Typed",
    "Development Status :: 4 - Beta",
    "Environment :: Web Environment",
    "Framework :: AsyncIO",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Topic :: Internet :: WWW/HTTP :: HTTP Servers",
    "Topic :: Internet :: WWW/HTTP",
    "Topic :: Utilities"
]

[tool.poetry.dependencies]
python = "^3.6"

fastapi = "*"
pydantic = "^1.0"
sqlalchemy = "^1.3.12"

[tool.poetry.dev-dependencies]
# Starlette features
wheel = "*"
aiofiles = "*"  # Serving static files
requests = "*"  # TestClient

# Testing
pytest = "~=5.4.3"
pytest-cov = "*"
pytest-asyncio = "*"
coverage = "*"

# Python 3.6 Testing
async-exit-stack = { version = "*", python = "~3.6" }
async-generator = { version = "*", python = "~3.6" }

# CI
codecov = "*"

# Static
isort = "*"
autoflake = "*"
black = { version = "*", allow-prereleases = true }
flake8 = "*"
mypy = "*"
sqlalchemy-stubs = "*"

# Documentation
mkdocs = "*"
mkdocs-material = "*"
markdown-include = "*"

[tool.black]
line-length = 120
target_version = ['py37']
include = '\.pyi?$'
exclude = '''
(
  /(
    \.git
    | \.mypy_cache
    | \.pytest_cache
    | htmlcov
    | build
  )/
)
'''

[tool.isort]
line_length = 120
known_first_party = ["fastapi-utils", "tests"]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
combine_as_imports = true

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
